//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatCanICook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favorite_Recipes
    {
        public string favourite_recipe_name { get; set; }
        public int users_id { get; set; }
        public string recipe_id { get; set; }
    
        public virtual Recipe Recipe { get; set; }
        public virtual User User { get; set; }
    }
}
