//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhatCanICook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int users_id { get; set; }
        public string user_firstName { get; set; }
        public string user_lastName { get; set; }
        public string user_email { get; set; }
        public string user_password { get; set; }
        public string user_foodType { get; set; }
        public string user_type { get; set; }
    
        public virtual Favorite_Recipes Favorite_Recipes { get; set; }
    }
}
